
import fetch from 'node-fetch';

const llantas = [
  {
    "nombreLLanta": "Llanta Fiat",
    "precio": 2621090,
    "marca": "Fiat",
    "modelo": "Modelo 1",
    "material": "Aluminio",
    "diametro": 18,
    "ancho": 7,
    "stock": 0,
    "alto": "55",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Chevrolet",
    "precio": 2707870,
    "marca": "Chevrolet",
    "modelo": "Modelo 2",
    "material": "Hierro",
    "diametro": 16,
    "ancho": 7,
    "stock": 5,
    "alto": "54",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Ford",
    "precio": 2602392,
    "marca": "Ford",
    "modelo": "Modelo 3",
    "material": "Aluminio",
    "diametro": 17,
    "ancho": 7,
    "stock": 5,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Renault",
    "precio": 3746013,
    "marca": "Renault",
    "modelo": "Modelo 4",
    "material": "Hierro",
    "diametro": 20,
    "ancho": 9,
    "stock": 5,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Peugeot",
    "precio": 2702295,
    "marca": "Peugeot",
    "modelo": "Modelo 5",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 7,
    "stock": 5,
    "alto": "54",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Toyota",
    "precio": 3204917,
    "marca": "Toyota",
    "modelo": "Modelo 6",
    "material": "Hierro",
    "diametro": 18,
    "ancho": 10,
    "stock": 0,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Volkswagen",
    "precio": 2397268,
    "marca": "Volkswagen",
    "modelo": "Modelo 7",
    "material": "Aluminio",
    "diametro": 15,
    "ancho": 9,
    "stock": 5,
    "alto": "48",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": false
  },
  {
    "nombreLLanta": "Llanta Honda",
    "precio": 2778515,
    "marca": "Honda",
    "modelo": "Modelo 8",
    "material": "Magnesio",
    "diametro": 15,
    "ancho": 9,
    "stock": 0,
    "alto": "55",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Nissan",
    "precio": 2033382,
    "marca": "Nissan",
    "modelo": "Modelo 9",
    "material": "Hierro",
    "diametro": 16,
    "ancho": 7,
    "stock": 0,
    "alto": "52",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta BMW",
    "precio": 2713319,
    "marca": "BMW",
    "modelo": "Modelo 10",
    "material": "Aluminio",
    "diametro": 19,
    "ancho": 7,
    "stock": 5,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Audi",
    "precio": 3090416,
    "marca": "Audi",
    "modelo": "Modelo 11",
    "material": "Aluminio",
    "diametro": 17,
    "ancho": 10,
    "stock": 5,
    "alto": "48",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Mercedes",
    "precio": 3115611,
    "marca": "Mercedes",
    "modelo": "Modelo 12",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 7,
    "stock": 5,
    "alto": "48",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Citroen",
    "precio": 3959615,
    "marca": "Citroen",
    "modelo": "Modelo 13",
    "material": "Hierro",
    "diametro": 16,
    "ancho": 8,
    "stock": 0,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Jeep",
    "precio": 2376899,
    "marca": "Jeep",
    "modelo": "Modelo 14",
    "material": "Aluminio",
    "diametro": 18,
    "ancho": 6,
    "stock": 5,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Kia",
    "precio": 3580451,
    "marca": "Kia",
    "modelo": "Modelo 15",
    "material": "Aluminio",
    "diametro": 16,
    "ancho": 10,
    "stock": 5,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Hyundai",
    "precio": 3276224,
    "marca": "Hyundai",
    "modelo": "Modelo 16",
    "material": "Magnesio",
    "diametro": 15,
    "ancho": 9,
    "stock": 0,
    "alto": "53",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Mazda",
    "precio": 3787297,
    "marca": "Mazda",
    "modelo": "Modelo 17",
    "material": "Aluminio",
    "diametro": 17,
    "ancho": 8,
    "stock": 0,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Volvo",
    "precio": 2357558,
    "marca": "Volvo",
    "modelo": "Modelo 18",
    "material": "Hierro",
    "diametro": 14,
    "ancho": 8,
    "stock": 5,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Subaru",
    "precio": 3324077,
    "marca": "Subaru",
    "modelo": "Modelo 19",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 6,
    "stock": 5,
    "alto": "52",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Tesla",
    "precio": 3842768,
    "marca": "Tesla",
    "modelo": "Modelo 20",
    "material": "Aluminio",
    "diametro": 18,
    "ancho": 8,
    "stock": 0,
    "alto": "54",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Alfa Romeo",
    "precio": 2233424,
    "marca": "Alfa Romeo",
    "modelo": "Modelo 21",
    "material": "Aluminio",
    "diametro": 15,
    "ancho": 8,
    "stock": 0,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Dodge",
    "precio": 2095329,
    "marca": "Dodge",
    "modelo": "Modelo 22",
    "material": "Hierro",
    "diametro": 18,
    "ancho": 9,
    "stock": 5,
    "alto": "49",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Chrysler",
    "precio": 3583975,
    "marca": "Chrysler",
    "modelo": "Modelo 23",
    "material": "Aluminio",
    "diametro": 16,
    "ancho": 10,
    "stock": 5,
    "alto": "53",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": false
  },
  {
    "nombreLLanta": "Llanta Lexus",
    "precio": 2103386,
    "marca": "Lexus",
    "modelo": "Modelo 24",
    "material": "Magnesio",
    "diametro": 14,
    "ancho": 7,
    "stock": 0,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Jaguar",
    "precio": 2389890,
    "marca": "Jaguar",
    "modelo": "Modelo 25",
    "material": "Hierro",
    "diametro": 16,
    "ancho": 8,
    "stock": 0,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Land Rover",
    "precio": 2732469,
    "marca": "Land Rover",
    "modelo": "Modelo 26",
    "material": "Hierro",
    "diametro": 18,
    "ancho": 9,
    "stock": 0,
    "alto": "52",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": false
  },
  {
    "nombreLLanta": "Llanta Mini",
    "precio": 2986298,
    "marca": "Mini",
    "modelo": "Modelo 27",
    "material": "Aluminio",
    "diametro": 17,
    "ancho": 6,
    "stock": 5,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Smart",
    "precio": 3547164,
    "marca": "Smart",
    "modelo": "Modelo 28",
    "material": "Aluminio",
    "diametro": 15,
    "ancho": 9,
    "stock": 5,
    "alto": "53",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Suzuki",
    "precio": 3242534,
    "marca": "Suzuki",
    "modelo": "Modelo 29",
    "material": "Hierro",
    "diametro": 19,
    "ancho": 7,
    "stock": 5,
    "alto": "52",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Mitsubishi",
    "precio": 2999784,
    "marca": "Mitsubishi",
    "modelo": "Modelo 30",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 7,
    "stock": 0,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Isuzu",
    "precio": 2899082,
    "marca": "Isuzu",
    "modelo": "Modelo 31",
    "material": "Magnesio",
    "diametro": 19,
    "ancho": 6,
    "stock": 5,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Seat",
    "precio": 3986397,
    "marca": "Seat",
    "modelo": "Modelo 32",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 10,
    "stock": 0,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Skoda",
    "precio": 2555917,
    "marca": "Skoda",
    "modelo": "Modelo 33",
    "material": "Aluminio",
    "diametro": 20,
    "ancho": 7,
    "stock": 5,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Saab",
    "precio": 3967092,
    "marca": "Saab",
    "modelo": "Modelo 34",
    "material": "Magnesio",
    "diametro": 14,
    "ancho": 8,
    "stock": 5,
    "alto": "54",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": false
  },
  {
    "nombreLLanta": "Llanta Opel",
    "precio": 3566391,
    "marca": "Opel",
    "modelo": "Modelo 35",
    "material": "Hierro",
    "diametro": 17,
    "ancho": 8,
    "stock": 5,
    "alto": "49",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Daewoo",
    "precio": 2572878,
    "marca": "Daewoo",
    "modelo": "Modelo 36",
    "material": "Hierro",
    "diametro": 19,
    "ancho": 7,
    "stock": 0,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": false
  },
  {
    "nombreLLanta": "Llanta Geely",
    "precio": 2967860,
    "marca": "Geely",
    "modelo": "Modelo 37",
    "material": "Hierro",
    "diametro": 19,
    "ancho": 8,
    "stock": 0,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Great Wall",
    "precio": 2634970,
    "marca": "Great Wall",
    "modelo": "Modelo 38",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 8,
    "stock": 0,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Chery",
    "precio": 2841897,
    "marca": "Chery",
    "modelo": "Modelo 39",
    "material": "Hierro",
    "diametro": 18,
    "ancho": 10,
    "stock": 5,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta BYD",
    "precio": 2714483,
    "marca": "BYD",
    "modelo": "Modelo 40",
    "material": "Aluminio",
    "diametro": 19,
    "ancho": 7,
    "stock": 5,
    "alto": "51",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Mahindra",
    "precio": 2569204,
    "marca": "Mahindra",
    "modelo": "Modelo 41",
    "material": "Magnesio",
    "diametro": 17,
    "ancho": 7,
    "stock": 5,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Tata",
    "precio": 3725809,
    "marca": "Tata",
    "modelo": "Modelo 42",
    "material": "Magnesio",
    "diametro": 19,
    "ancho": 10,
    "stock": 0,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Lifan",
    "precio": 3783587,
    "marca": "Lifan",
    "modelo": "Modelo 43",
    "material": "Magnesio",
    "diametro": 19,
    "ancho": 10,
    "stock": 0,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Dongfeng",
    "precio": 3994245,
    "marca": "Dongfeng",
    "modelo": "Modelo 44",
    "material": "Aluminio",
    "diametro": 16,
    "ancho": 10,
    "stock": 0,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Zotye",
    "precio": 2357237,
    "marca": "Zotye",
    "modelo": "Modelo 45",
    "material": "Aluminio",
    "diametro": 14,
    "ancho": 6,
    "stock": 5,
    "alto": "54",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta FAW",
    "precio": 2394701,
    "marca": "FAW",
    "modelo": "Modelo 46",
    "material": "Hierro",
    "diametro": 19,
    "ancho": 10,
    "stock": 5,
    "alto": "56",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta BAIC",
    "precio": 2000944,
    "marca": "BAIC",
    "modelo": "Modelo 47",
    "material": "Hierro",
    "diametro": 17,
    "ancho": 9,
    "stock": 5,
    "alto": "50",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta DS",
    "precio": 3543091,
    "marca": "DS",
    "modelo": "Modelo 48",
    "material": "Magnesio",
    "diametro": 16,
    "ancho": 7,
    "stock": 0,
    "alto": "53",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Proton",
    "precio": 3946630,
    "marca": "Proton",
    "modelo": "Modelo 49",
    "material": "Aluminio",
    "diametro": 15,
    "ancho": 6,
    "stock": 0,
    "alto": "53",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  },
  {
    "nombreLLanta": "Llanta Fiat",
    "precio": 2137776,
    "marca": "Fiat",
    "modelo": "Modelo 50",
    "material": "Aluminio",
    "diametro": 14,
    "ancho": 7,
    "stock": 0,
    "alto": "47",
    "urlIMG": "Front\\images\\assets\\primer-plano-de-pato-de-goma.jpg",
    "activo": true
  }
];

llantas.forEach(async (data) => {
  const obj = {
    nombreLLanta: data.nombreLLanta,
    precio: data.precio,
    marca: data.marca,
    modelo: data.modelo,
    material: data.material,
    diametro: data.diametro,
    ancho: data.ancho,
    alto: parseInt(data.alto),
    stock: data.stock,
    urlIMG: data.urlIMG.replace(/\\/g, "/"),
    activo: data.activo
  };

  console.log("Enviando", obj);

  try {
    const res = await fetch('http://localhost:5000/api/llanta', {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(obj),
    });

    const result = await res.json();
    console.log(`✔ Llanta ${obj.nombreLLanta} creada:`, result);
  } catch (err) {
    console.error(`❌ Error al enviar Llanta ${obj.nombreLLanta}:`, err.message);
  }
});
// profe en caso de prueba utilizar este comando node C:\Users\lunam\OneDrive\Documentos\GitHub\EstiloRodante_2\Front\client\js\enviarLlantas.js

const adminLink = document.querySelector('.admin-link');
adminLink.addEventListener('click', (e) => {
  e.preventDefault();
  window.location.href = 'http://localhost:5000/admin';
});